# Generated by Django 4.2.7 on 2026-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[("creator", "Creator"), ("fan", "Fan")],
                default="fan",
                help_text="Select account type: Creator or Fan",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="favorite_genres",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of favorite genres",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_instagram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_twitter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_youtube",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(
                blank=True, help_text="Creator's website or portfolio", null=True
            ),
        ),
    ]
