# Generated by Django 4.2.7 on 2026-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="account_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="goal_weight",
            field=models.IntegerField(
                blank=True, help_text="Goal weight in lbs", null=True
            ),
        ),
    ]
