# Generated by Django 4.2.7 on 2026-06-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_account_type_profile_goal_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="favorite_genres",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_instagram",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_twitter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_youtube",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
    ]
