# Generated by Django 4.2.7 on 2026-06-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_workoutlog_userstreak_usersettings_pointstransaction_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personalbest",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="gymmembership",
            name="fitness_goal",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="sms_notifications",
        ),
    ]
