# Generated by Django 4.2.7 on 2026-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="expense", max_length=50)),
                ("description", models.TextField(default="")),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
