# Generated by Django 4.2.7 on 2026-06-16 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("godmode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
