# Generated by Django 4.2.7 on 2026-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godmode", "0002_expense_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("date_received", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_received"],
            },
        ),
    ]
