# Generated by Django 4.2.7 on 2026-06-16 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_personalbest_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("godmode", "0003_income"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("missed", "Missed"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("checkin_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="home.gymmembership",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checkin_date", "-checkin_time"],
                "unique_together": {("member", "checkin_date")},
            },
        ),
    ]
