# Generated by Django 4.2.7 on 2026-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("godmode", "0004_dailycheckin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("faulty", "Faulty"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
